import amuBl      from '../assets/ath.jersey/amu_bl.jpeg';
import amuB       from '../assets/ath.jersey/amu_b.jpeg';
import hills      from '../assets/ath.jersey/hills.jpeg';
import purvanchal from '../assets/ath.jersey/purvanchal.jpeg';
import purv       from '../assets/ath.jersey/purv.jpeg';
import nameImg    from '../assets/ath.jersey/name.jpeg';
import oceanday   from '../assets/ath.jersey/oceanday.jpeg';
import rcb2       from '../assets/ath.jersey/rcb2.jpeg';
import rcbblack   from '../assets/ath.jersey/rcbblack.jpeg';
import rcbred     from '../assets/ath.jersey/rcbred.jpeg';
import prabhukul  from '../assets/ath.jersey/prabhukul.jpeg';
import sakshiT    from '../assets/ath.jersey/sakshiiii_t.jpeg';
import sakshiS    from '../assets/ath.jersey/sakshitraders.jpeg';
import d21        from '../assets/ath.jersey/D 2 1.png';
import d3         from '../assets/ath.jersey/D 3.png';
import d22        from '../assets/ath.jersey/D2 2.png';
import design     from '../assets/ath.jersey/Design.png';
import friend1    from '../assets/ath.jersey/Friend 1.png';
import friend2    from '../assets/ath.jersey/Friend 2.png';
import offer1     from '../assets/ath.jersey/Offer 1.png';
import offer2     from '../assets/ath.jersey/Offer 2.png';
import offer3     from '../assets/ath.jersey/Offer 3.png';
import offer4     from '../assets/ath.jersey/Offer 4.png';
import team1      from '../assets/ath.jersey/Team 1.png';
import team2      from '../assets/ath.jersey/Team 2.png';
import team3      from '../assets/ath.jersey/Team 3.png';
import wa1        from '../assets/ath.jersey/WhatsApp Image 2026-06-22 at 8.33.08 AM.jpeg';
import wa2        from '../assets/ath.jersey/WhatsApp Image 2026-06-22 at 8.33.09 AM (2).jpeg';
import offer5     from '../assets/ath.jersey/offer 5.png';
import offer6     from '../assets/ath.jersey/offer 6.png';

export const mockProducts = [
  {
    "_id": "p1",
    "name": "AMU Blue Striker",
    "code": "ATH-JY-001",
    "category": "Jerseys",
    "price": 1299,
    "description": "Premium AMU edition blue striker jersey. Breathable polyester mesh, moisture-wicking fabric crafted for high performance and style.",
    "fabric": "100% Polyester Mesh",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#2563eb", "#000000"],
    "colorNames": ["Blue", "Black"],
    "images": [amuBl, amuB],
    "isActive": true,
    "isFeatured": true,
    "stockStatus": "In Stock",
    "tags": ["amu", "blue", "striker", "football"]
  },
  {
    "_id": "p2",
    "name": "Hills FC Classic",
    "code": "ATH-JY-002",
    "category": "Jerseys",
    "price": 1199,
    "description": "Hills FC classic edition jersey. Lightweight and durable — perfect for match days and training sessions.",
    "fabric": "88% Polyester, 12% Spandex",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#16a34a", "#ffffff"],
    "colorNames": ["Green", "White"],
    "images": [hills, purv],
    "isActive": true,
    "isFeatured": true,
    "stockStatus": "In Stock",
    "tags": ["hills", "football", "classic"]
  },
  {
    "_id": "p3",
    "name": "Purvanchal Legacy",
    "code": "ATH-JY-003",
    "category": "Jerseys",
    "price": 1399,
    "description": "Purvanchal legacy jersey with bold design. A tribute to the spirit of the region — wear it with pride.",
    "fabric": "70% Cotton, 30% Polyester",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#eab308", "#1e3a8a"],
    "colorNames": ["Yellow", "Navy"],
    "images": [purvanchal, prabhukul],
    "isActive": true,
    "isFeatured": true,
    "stockStatus": "In Stock",
    "tags": ["purvanchal", "legacy", "football"]
  },
  {
    "_id": "p4",
    "name": "RCB Flame Edition",
    "code": "ATH-JY-004",
    "category": "Jerseys",
    "price": 1599,
    "description": "RCB Flame edition — iconic red and black combination. Feel the fire every time you wear it.",
    "fabric": "100% Polyester Mesh",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#dc2626", "#000000"],
    "colorNames": ["Red", "Black"],
    "images": [rcbred, rcb2],
    "isActive": true,
    "isFeatured": true,
    "stockStatus": "In Stock",
    "tags": ["rcb", "cricket", "red", "premium"]
  },
  {
    "_id": "p5",
    "name": "RCB Dark Knight",
    "code": "ATH-JY-005",
    "category": "Jerseys",
    "price": 1599,
    "description": "RCB Dark Knight edition in sleek all-black with signature red accents. Limited collector's jersey.",
    "fabric": "90% Nylon, 10% Elastane",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#000000", "#dc2626"],
    "colorNames": ["Black", "Red"],
    "images": [rcbblack, rcb2],
    "isActive": true,
    "isFeatured": true,
    "stockStatus": "Limited Stock",
    "tags": ["rcb", "black", "dark", "cricket"]
  },
  {
    "_id": "p6",
    "name": "Ocean Wave Jersey",
    "code": "ATH-JY-006",
    "category": "Jerseys",
    "price": 1099,
    "description": "Ocean Wave jersey with refreshing blue tones. Sweat-wicking fabric keeps you cool all game long.",
    "fabric": "Recycled Microfiber",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#0284c7", "#ffffff"],
    "colorNames": ["Ocean Blue", "White"],
    "images": [oceanday, nameImg],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["ocean", "cool", "breathable"]
  },
  {
    "_id": "p7",
    "name": "Sakshi Traders Elite",
    "code": "ATH-JY-007",
    "category": "Jerseys",
    "price": 1499,
    "description": "Sakshi Traders elite jersey — custom crafted for clubs and teams. Premium finish with sublimation print.",
    "fabric": "100% Polyester Mesh",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#dc2626", "#ffffff"],
    "colorNames": ["Red", "White"],
    "images": [sakshiS, sakshiT],
    "isActive": true,
    "isFeatured": true,
    "stockStatus": "In Stock",
    "tags": ["sakshi", "elite", "custom", "club"]
  },
  {
    "_id": "p8",
    "name": "Comfy Design Pro",
    "code": "ATH-JY-008",
    "category": "Jerseys",
    "price": 1350,
    "description": "Comfy Design Pro jersey with bold graphic print. Stands out on the field and off it.",
    "fabric": "88% Polyester, 12% Spandex",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#7c3aed", "#000000"],
    "colorNames": ["Purple", "Black"],
    "images": [design, d22],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["design", "pro", "graphic"]
  },
  {
    "_id": "p9",
    "name": "D-Series Bolt Jersey",
    "code": "ATH-JY-009",
    "category": "Jerseys",
    "price": 1250,
    "description": "D-Series Bolt jersey — fast, fierce, and full of energy. Built for the athlete who never stops.",
    "fabric": "70% Cotton, 30% Polyester",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#f59e0b", "#111827"],
    "colorNames": ["Amber", "Dark"],
    "images": [d21, d3],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["d-series", "bolt", "football"]
  },
  {
    "_id": "p10",
    "name": "D-Series Storm",
    "code": "ATH-JY-010",
    "category": "Jerseys",
    "price": 1250,
    "description": "D-Series Storm edition jersey. Dynamic patterns that mirror the storm on the pitch.",
    "fabric": "100% Polyester Mesh",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#1d4ed8", "#ffffff"],
    "colorNames": ["Blue", "White"],
    "images": [d22, design],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "Limited Stock",
    "tags": ["d-series", "storm", "football"]
  },
  {
    "_id": "p11",
    "name": "Comfy Match Kit I",
    "code": "ATH-JY-011",
    "category": "Jerseys",
    "price": 999,
    "description": "Comfy Match Kit I — affordable and durable jersey for weekend warriors and school teams.",
    "fabric": "Merino Wool Blend",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#16a34a", "#ffffff"],
    "colorNames": ["Green", "White"],
    "images": [friend1, friend2],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["match", "kit", "affordable"]
  },
  {
    "_id": "p12",
    "name": "Comfy Match Kit II",
    "code": "ATH-JY-012",
    "category": "Jerseys",
    "price": 999,
    "description": "Comfy Match Kit II — second edition with improved stitching and vibrant colour retention.",
    "fabric": "Merino Wool Blend",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#dc2626", "#000000"],
    "colorNames": ["Red", "Black"],
    "images": [friend2, friend1],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["match", "kit", "affordable"]
  },
  {
    "_id": "p13",
    "name": "Sprint Series I",
    "code": "ATH-JY-013",
    "category": "Jerseys",
    "price": 1150,
    "description": "Sprint Series I jersey — designed for speed lovers. Ultra-light construction with anti-odour treatment.",
    "fabric": "100% Polyester Mesh",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#2563eb", "#ffffff"],
    "colorNames": ["Blue", "White"],
    "images": [offer1, offer2],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["sprint", "speed", "football"]
  },
  {
    "_id": "p14",
    "name": "Sprint Series II",
    "code": "ATH-JY-014",
    "category": "Jerseys",
    "price": 1150,
    "description": "Sprint Series II — second wave, same speed. Enhanced breathability for hot-weather matches.",
    "fabric": "90% Nylon, 10% Elastane",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#16a34a", "#000000"],
    "colorNames": ["Green", "Black"],
    "images": [offer2, offer3],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["sprint", "breathable", "football"]
  },
  {
    "_id": "p15",
    "name": "Sprint Series III",
    "code": "ATH-JY-015",
    "category": "Jerseys",
    "price": 1150,
    "description": "Sprint Series III with reinforced shoulder stitching and sweat-lock collar. Game-ready from the first whistle.",
    "fabric": "88% Polyester, 12% Spandex",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#dc2626", "#ffffff"],
    "colorNames": ["Red", "White"],
    "images": [offer3, offer4],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["sprint", "reinforced", "football"]
  },
  {
    "_id": "p16",
    "name": "Sprint Series IV",
    "code": "ATH-JY-016",
    "category": "Jerseys",
    "price": 1150,
    "description": "Sprint Series IV — limited run with exclusive patch embroidery. Collector's pick for jersey enthusiasts.",
    "fabric": "100% Polyester Mesh",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#7c3aed", "#ffffff"],
    "colorNames": ["Purple", "White"],
    "images": [offer4, offer1],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "Limited Stock",
    "tags": ["sprint", "limited", "collector"]
  },
  {
    "_id": "p17",
    "name": "Team Force Jersey I",
    "code": "ATH-JY-017",
    "category": "Jerseys",
    "price": 1799,
    "description": "Team Force Jersey I — bulk-order ready, custom name & number printing available. Ideal for clubs.",
    "fabric": "70% Cotton, 30% Polyester",
    "sizes": ["S", "M", "L", "XL", "XXL", "XXXL"],
    "colors": ["#1e3a8a", "#ffffff"],
    "colorNames": ["Navy", "White"],
    "images": [team1, team2],
    "isActive": true,
    "isFeatured": true,
    "stockStatus": "In Stock",
    "tags": ["team", "club", "bulk", "custom"]
  },
  {
    "_id": "p18",
    "name": "Team Force Jersey II",
    "code": "ATH-JY-018",
    "category": "Jerseys",
    "price": 1799,
    "description": "Team Force Jersey II with advanced moisture management. Perfect for 90-minute full matches.",
    "fabric": "Recycled Microfiber",
    "sizes": ["S", "M", "L", "XL", "XXL", "XXXL"],
    "colors": ["#dc2626", "#000000"],
    "colorNames": ["Red", "Black"],
    "images": [team2, team3],
    "isActive": true,
    "isFeatured": true,
    "stockStatus": "In Stock",
    "tags": ["team", "club", "bulk", "custom"]
  },
  {
    "_id": "p19",
    "name": "Team Force Jersey III",
    "code": "ATH-JY-019",
    "category": "Jerseys",
    "price": 1799,
    "description": "Team Force Jersey III — third edition with reflective strips for evening training sessions.",
    "fabric": "90% Nylon, 10% Elastane",
    "sizes": ["S", "M", "L", "XL", "XXL", "XXXL"],
    "colors": ["#16a34a", "#000000"],
    "colorNames": ["Green", "Black"],
    "images": [team3, team1],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["team", "reflective", "evening", "custom"]
  },
  {
    "_id": "p20",
    "name": "Pro Offer Jersey V",
    "code": "ATH-JY-020",
    "category": "Jerseys",
    "price": 1099,
    "description": "Pro Offer Jersey V — best value in our lineup. Full sublimation print, anti-pilling fabric.",
    "fabric": "100% Polyester Mesh",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#f59e0b", "#000000"],
    "colorNames": ["Amber", "Black"],
    "images": [offer5, offer6],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["offer", "value", "sublimation"]
  },
  {
    "_id": "p21",
    "name": "Pro Offer Jersey VI",
    "code": "ATH-JY-021",
    "category": "Jerseys",
    "price": 1099,
    "description": "Pro Offer Jersey VI — vibrant colours, long-lasting print. Great for gifting and tournaments.",
    "fabric": "88% Polyester, 12% Spandex",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#dc2626", "#ffffff"],
    "colorNames": ["Red", "White"],
    "images": [offer6, offer5],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["offer", "gift", "tournament"]
  },
  {
    "_id": "p22",
    "name": "Custom Club Jersey I",
    "code": "ATH-JY-022",
    "category": "Jerseys",
    "price": 1349,
    "description": "Custom Club Jersey I — tailor-made for your squad. Send your logo, get your jersey in 7 days.",
    "fabric": "100% Polyester Mesh",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#1d4ed8", "#ffffff"],
    "colorNames": ["Blue", "White"],
    "images": [wa1, hills],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["custom", "club", "logo", "squad"]
  },
  {
    "_id": "p23",
    "name": "Custom Club Jersey II",
    "code": "ATH-JY-023",
    "category": "Jerseys",
    "price": 1349,
    "description": "Custom Club Jersey II — premium edition with woven badge support. Full team kits available.",
    "fabric": "Merino Wool Blend",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#000000", "#dc2626"],
    "colorNames": ["Black", "Red"],
    "images": [wa2, amuBl],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "Limited Stock",
    "tags": ["custom", "club", "badge", "premium"]
  },
  {
    "_id": "p24",
    "name": "Purvanchal Special",
    "code": "ATH-JY-024",
    "category": "Jerseys",
    "price": 1299,
    "description": "Purvanchal Special edition — exclusive regional jersey celebrating local football culture.",
    "fabric": "70% Cotton, 30% Polyester",
    "sizes": ["S", "M", "L", "XL", "XXL"],
    "colors": ["#eab308", "#1e3a8a"],
    "colorNames": ["Yellow", "Navy"],
    "images": [purv, purvanchal],
    "isActive": true,
    "isFeatured": false,
    "stockStatus": "In Stock",
    "tags": ["purvanchal", "regional", "special"]
  },
  {
    "_id": "p25",
    "name": "Sakshi Pro Trader Kit",
    "code": "ATH-JY-025",
    "category": "Jerseys",
    "price": 1499,
    "description": "Sakshi Pro Trader Kit — wholesale-grade jersey with retail-quality finish. Bulk orders welcome.",
    "fabric": "100% Polyester Mesh",
    "sizes": ["S", "M", "L", "XL", "XXL", "XXXL"],
    "colors": ["#dc2626", "#000000"],
    "colorNames": ["Red", "Black"],
    "images": [sakshiT, sakshiS],
    "isActive": true,
    "isFeatured": true,
    "stockStatus": "In Stock",
    "tags": ["sakshi", "wholesale", "bulk", "pro"]
  }
];
